import "./globals.css";
import { Cardo, Roboto } from "next/font/google";

const cardo = Cardo({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-cardo",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Downunder Landscape",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${cardo.variable} ${roboto.variable}`}>
      <body>{children}</body>
    </html>
  );
}
